### PR TITLE
Add NixOS Guide

### PR DESCRIPTION
**Pull request by TimP4w**
As discussed in #45 I'm creating a PR to add the NixOS guide.

@theNizo had some time to test more configurations and this is a minimal one, that doesn't require musnix and would also make VBASIOTest work.

### CODE REVIEW

**Comment by TimP4w** [comment]
@theNizo  had some time to test more configurations and this is a minimal one, that doesn't require musnix and would also make VBASIOTest work.

**Review by theNizo — APPROVED** [review]
* Line 123: As far as I can tell, the username after /home/ is missing.
* (Manual) Step 3: we didn't install wineasio yet, did we? (see note at the bottom)

Thank you for the submission. If that's okay for you, I'll mention you in the credits section.

If that's okay for you, I'll rework the guide. Since I wrote the other guides, I can understand every step I should take, but I would add other steps not mentioned yet like the troubleshooting and CDLC section.

**Comment by TimP4w** [comment]
> Line 123: As far as I can tell, the username after /home/ is missing.

Yep...

> (Manual) Step 3: we didn't install wineasio yet, did we? (see note at the bottom)

We already did when we applied the config for NixOS (Step 1).  In nixos when you rebuild your system, it installs the dependencies you specified in the config.

For the rest, go for it!

**Comment by TimP4w** [comment]
Btw. @theNizo ich kann eventuell deine PR/commit auch reviewen, um zu sehen, ob etwas für NixOS anders gemacht werden soll.

**Comment by theNizo** [comment]
Bin grad überrascht, dass du auf einmal auf deutsch schreibst.

Ja, gerne.

**Pull request merged**
