### PR TITLE
fixed missing sudo commands

### PR DESCRIPTION
**Pull request by memejim8**
thats it

### CODE REVIEW

**Comment by theNizo** [comment]
`find` needs the user running it to have the read permission. I can confirm that this is the default for system directories on vanilla Arch as well as Manjaro.

This pull request suggests that this isn't the case on the distro you use. If that is correct, I'm interested which distro it is.

**Comment by theNizo** [comment]
Note to myself, if I accept this, I'd have to edit [src](https://github.com/theNizo/linux_rocksmith/tree/main/src) to fit the change.

**Comment by memejim8** [comment]
i use manjaro and with sudo there are no errors

**Comment by theNizo** [comment]
Okay, I just noticed that I once was aware of the errors. I mentioned them in a sentence just below these edits (you missed that, but that's okay). So here's what I think:

- Even if there are errors, it outputs the correct amount of paths. So it's not that pretty, but it works fine without sudo.
- There's a security reason why you are not root, but just a normal user. If you go a step further, it sounds like bad practice to run something as root that doesn't need elevated privileges. Mindlessly using sudo is not a habit I would want to encourage. I therefore would like to keep it as it is.

If you have a different view, please share.

**Pull request closed without merging**
